version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERES=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENERES=yes
    depends_on:
      - zookeeper
  
  server:
    image: 'kafka-server'
    container_name: server
    build: 
      context: server
    environment:
      - PORT=8080
    depends_on:
      - kafka
  producer:
    image: 'producer:latest'
    container_name: kafka-producer
    build:
      context: producer
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - server
  consumer:
    image: 'consumer:latest'
    container_name: kafka-consumer
    build:
      context: consumer
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - producer
  web:
    image: 'project1'
    build: 
      dockerfile: Dockerfile
    volumes:
      - .:/app 
    ports:
      - "5000:8000"
